In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

# Binary Classification

In [27]:
df = pd.read_csv("../../datasets/student_binary_classification1.csv")
df

    StudyHours     Result
0          1.0       Fail
1          2.0       Fail
2          2.5       Fail
3          3.0       Good
4          3.5       Good
5          4.0       Good
6          4.5       Good
7          5.0    Average
8          5.5    Average
9          6.0    Average
10         7.0  Excellent
11         8.0  Excellent

In [28]:
# encoding 

df["Result"]=df["Result"].map({
    "Fail" : 0,
    "Good" : 1,
    "Average" : 2,
    "Excellent" : 3
})
df

    StudyHours  Result
0          1.0       0
1          2.0       0
2          2.5       0
3          3.0       1
4          3.5       1
5          4.0       1
6          4.5       1
7          5.0       2
8          5.5       2
9          6.0       2
10         7.0       3
11         8.0       3

In [29]:
# features selection

X = df[["StudyHours"]]
y = df["Result"]

In [17]:
# train_test_split

In [30]:
model = DecisionTreeClassifier(
    criterion = "gini",
    random_state= 42
)

In [31]:
# model train 

model.fit(X, y)

DecisionTreeClassifier(random_state=42)

In [33]:
print(model.tree_.threshold)

[ 2.75 -2.    4.75 -2.    6.5  -2.   -2.  ]

In [34]:
new_student = pd.DataFrame({
    "StudyHours": [2,3,5]
})

predicition = model.predict(new_student)
print(predicition)

[0 1 2]

# multiple feature multi Classification

In [38]:
df = pd.read_csv("../../datasets/student_multiclass_multiple_features.csv")
df

    Student  StudyHours  Attendance  PreviousMarks   Result
0     Aarav           1          55             28     Fail
1      Sita           2          60             32     Fail
2       Ram           2          65             36     Fail
3    Anisha           3          70             40     Fail
4     Rohan           3          72             43     Fail
5     Priya           4          75             48  Average
6     Kiran           4          78             52  Average
7     Nabin           5          80             56  Average
8     Suman           5          82             60  Average
9    Alisha           5          84             63  Average
10   Bikash           6          86             67     Good
11   Sabina           6          88             70     Good
12   Roshan           6          90             73     Good
13     Puja           7          91             76     Good
14   Manish           7          92             79     Good
15     Rita           7          93             82     Good
16    Deepa           8          94             84     Good
17   Sanjay           8          95             87     Good
18   Kushal           8          96             89     Good
19   Aakash           9          97             91     Good
20     Bina           9          90             75     Good
21  Nischal           9          94             85     Good
22    Rekha          10          98             93     Good
23    Sagar          10          99             95     Good
24     Mina          10          96             90     Good

In [39]:
# encoding 

df["Result"]=df["Result"].map({
    "Fail" : 0,
    "Average" : 1,
    "Good" : 2
})
df

    Student  StudyHours  Attendance  PreviousMarks  Result
0     Aarav           1          55             28       0
1      Sita           2          60             32       0
2       Ram           2          65             36       0
3    Anisha           3          70             40       0
4     Rohan           3          72             43       0
5     Priya           4          75             48       1
6     Kiran           4          78             52       1
7     Nabin           5          80             56       1
8     Suman           5          82             60       1
9    Alisha           5          84             63       1
10   Bikash           6          86             67       2
11   Sabina           6          88             70       2
12   Roshan           6          90             73       2
13     Puja           7          91             76       2
14   Manish           7          92             79       2
15     Rita           7          93             82       2
16    Deepa           8          94             84       2
17   Sanjay           8          95             87       2
18   Kushal           8          96             89       2
19   Aakash           9          97             91       2
20     Bina           9          90             75       2
21  Nischal           9          94             85       2
22    Rekha          10          98             93       2
23    Sagar          10          99             95       2
24     Mina          10          96             90       2

In [42]:
# features selection

X = df[["StudyHours", "Attendance", "PreviousMarks"]]
y = df["Result"]

In [43]:
model = DecisionTreeClassifier(
    criterion = "gini",
    random_state= 42
)

In [44]:
# model train 

model.fit(X, y)

DecisionTreeClassifier(random_state=42)

In [45]:
new_student = pd.DataFrame({
    "StudyHours":[5],
    "Attendance":[60],
    "PreviousMarks": [70]
    
})

model.predict(new_student)

array([1])

# Multi Label

In [46]:
df = pd.read_csv("../../datasets/student_multilabel.csv")
df

   Student  StudyHours  EnglishScore  MathScore  PassEnglish  PassMath
0    Aarav           1            30         25            0         0
1     Sita           2            38         32            0         0
2      Ram           2            42         35            0         0
3   Anisha           3            45         40            0         0
4    Rohan           3            49         45            0         0
5    Priya           4            52         48            1         0
6    Kiran           4            58         42            1         0
7    Nabin           5            60         55            1         1
8    Suman           5            64         62            1         1
9   Alisha           6            68         58            1         1
10  Bikash           6            72         70            1         1
11  Sabina           7            75         65            1         1
12  Roshan           7            78         76            1         1
13    Puja           8            82         72            1         1
14  Manish           8            85         82            1         1
15    Rita           9            88         78            1         1
16   Deepa           9            90         88            1         1
17  Sanjay          10            92         85            1         1
18  Kushal          10            95         94            1         1
19    Mina          12            98         96            1         1

In [47]:
X = df[
    [
        "StudyHours",
        "EnglishScore",
        "MathScore"
    ]
]
y = df[
    [
        "PassEnglish",
        "PassMath"
    ]
]

In [48]:
model = DecisionTreeClassifier(
    criterion = "gini",
    random_state= 42
)

In [49]:
model.fit(X, y)

DecisionTreeClassifier(random_state=42)

In [50]:
new_studentss = pd.DataFrame({
    "StudyHours":[5],
    "EnglishScore":[80],
    "MathScore": [65]
})
model.predict(new_studentss)

array([[1, 1]])