In [1]:
import pandas as pd

In [3]:
dd = pd.read_csv("../datasets/bad_daraz_dataset.csv")
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,KaThmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,KATHMANDU,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,KAthmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [6]:
dd["price"]= pd.to_numeric(dd["price"], errors="coerce")
dd["price"]

0     75000.0
1         NaN
2      3500.0
3      1500.0
4      5500.0
5      4200.0
6     75000.0
7         NaN
8      1800.0
9      1800.0
10     2500.0
11      800.0
12    -2500.0
13    -2500.0
Name: price, dtype: float64

In [7]:
# Quartiles 

Q1 = dd["price"].quantile(0.25)
Q1

np.float64(1325.0)

In [8]:
# Quartiles

Q3 = dd["price"].quantile(0.75)
Q3

np.float64(4525.0)

In [19]:
# Median

median = dd["price"].median()
median

np.float64(2150.0)

In [9]:
# IQR

IQR = Q3-Q1
IQR

np.float64(3200.0)

In [11]:
# lower and upper bound
lower_bound = Q1-1.5*IQR
lower_bound

np.float64(-3475.0)

In [12]:
upper_bound = Q3+1.5*IQR
upper_bound

np.float64(9325.0)

In [13]:
outliers = dd[(dd["price"] < lower_bound)|(dd["price"] > upper_bound)]
outliers

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,KaThmandu,Dell,Unisex,25,120
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120

In [15]:
# count outliers
len(outliers)

2

In [17]:
# fix outliers with clip()

dd["price"].clip(lower_bound, upper_bound)

0     9325.0
1        NaN
2     3500.0
3     1500.0
4     5500.0
5     4200.0
6     9325.0
7        NaN
8     1800.0
9     1800.0
10    2500.0
11     800.0
12   -2500.0
13   -2500.0
Name: price, dtype: float64

In [21]:
# fix outliers with loc and median \

dd.loc[(dd["price"]<lower_bound)|(dd["price"]>upper_bound), "price"] = median
dd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,2150.0,10,4.8,25,TechHub,KaThmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,KATHMANDU,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,2150.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,KAthmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
12,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44