In [3]:
import pandas as pd

In [78]:
bdd = pd.read_csv("../datasets/bad_daraz_dataset.csv")
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,KaThmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,KATHMANDU,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,KAthmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [27]:
# bdd.isnull()  # detect null values , missing values
bdd.isnull().sum()   # sum of null values from each column

product_id          0
product_name        0
category            0
price               1
discount_percent    1
rating              1
stock               2
seller              0
city                0
brand               0
gender_target       0
age                 2
reviews             0
dtype: int64

In [28]:
# bdd.fillna(0)  # detect and fill missing values with zero

In [28]:
# bdd["price"].fillna(bdd["price"].mean())    # returns error cause string is in price column
bdd["price"] = pd.to_numeric(bdd["price"], errors = "coerce")  # convert string value into null value with no error
bdd
bdd["price"] = bdd["price"].fillna(bdd["price"].mean())  # filling in mean value in null value
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
13,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [29]:
bdd["age"] = pd.to_numeric(bdd["age"], errors ="coerce")
bdd["age"] = bdd["age"].fillna(bdd["age"].mean())
bdd

# bdd.dropna()  #drop/delete rows with null value

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
1,2,Phone,Electronics,13883.333333,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.000000,210
2,3,Shoes,Fashion,3500.000000,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.000000,55
3,4,T-Shirt,Fashion,1500.000000,20,NaN,150,Style,Biratnagar,Adidas,Female,24.444444,30
4,5,Watch,Accessories,5500.000000,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.000000,80
5,6,Headphones,Electronics,4200.000000,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.000000,65
6,7,Laptop,Electronics,75000.000000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
7,8,Bag,Fashion,13883.333333,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.000000,18
8,9,Mouse,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
9,9,Cup,Electronics,1800.000000,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
10,10,Keyboard,Electronics,2500.000000,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.000000,110
11,11,Bottle,Home,800.000000,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.000000,12
12,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44
13,12,Chair,Furniture,-2500.000000,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44

In [30]:
bdd["rating"]=pd.to_numeric(bdd["rating"], errors = "coerce")
bdd
bdd["rating"] = bdd["rating"].fillna(bdd["rating"].mean())
bdd["rating"]

0     4.800000
1     4.600000
2     4.200000
3     4.415385
4     4.500000
5     4.100000
6     4.800000
7     3.900000
8     4.300000
9     4.300000
10    4.400000
11    5.500000
12    4.000000
13    4.000000
Name: rating, dtype: float64

In [31]:
# bdd.duplicated()  # detect duplicated data

bdd[bdd.duplicated()]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
13,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44

In [32]:
# bdd["discount_percent"] = bdd["discount_percent"].str.replace("%","", regex=False)  # replace % from column
bdd
bdd["discount_percent"] = pd.to_numeric(bdd["discount_percent"], errors= "coerce")
bdd
bdd["discount_percent"] = bdd["discount_percent"].fillna(bdd["discount_percent"].mean())
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
1,2,Phone,Electronics,13883.333333,15.000000,4.600000,40,GadgetNepal,Pokhara,Samsung,Unisex,30.000000,210
2,3,Shoes,Fashion,3500.000000,9.333333,4.200000,60,FashionHub,Itahari,Nike,Male,22.000000,55
3,4,T-Shirt,Fashion,1500.000000,20.000000,4.415385,150,Style,Biratnagar,Adidas,Female,24.444444,30
4,5,Watch,Accessories,5500.000000,10.000000,4.500000,Out of Stock,TimeX,Kathmandu,Casio,Male,28.000000,80
5,6,Headphones,Electronics,4200.000000,9.333333,4.100000,75,AudioPro,Pokhara,JBL,Unisex,24.000000,65
6,7,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
7,8,Bag,Fashion,13883.333333,12.000000,3.900000,45,CarryAll,Dharan,Wildcraft,Female,19.000000,18
8,9,Mouse,Electronics,1800.000000,5.000000,4.300000,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
9,9,Cup,Electronics,1800.000000,5.000000,4.300000,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
10,10,Keyboard,Electronics,2500.000000,5.000000,4.400000,35,TechHub,Kathmandu,Logitech,Unisex,21.000000,110
11,11,Bottle,Home,800.000000,0.000000,5.500000,100,HomeStore,Janakpur,Generic,Unisex,26.000000,12
12,12,Chair,Furniture,-2500.000000,10.000000,4.000000,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44
13,12,Chair,Furniture,-2500.000000,10.000000,4.000000,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44

In [33]:
bdd["age"] = pd.to_numeric(bdd["age"], errors = "coerce")
bdd["age"]
bdd["age"]=bdd["age"].fillna(bdd["age"].mean())
bdd["age"]

0     25.000000
1     30.000000
2     22.000000
3     24.444444
4     28.000000
5     24.000000
6     25.000000
7     19.000000
8     24.444444
9     24.444444
10    21.000000
11    26.000000
12    24.444444
13    24.444444
Name: age, dtype: float64

In [36]:
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
1,2,Phone,Electronics,13883.333333,15.000000,4.600000,40,GadgetNepal,Pokhara,Samsung,Unisex,30.000000,210
2,3,Shoes,Fashion,3500.000000,9.333333,4.200000,60,FashionHub,Itahari,Nike,Male,22.000000,55
3,4,T-Shirt,Fashion,1500.000000,20.000000,4.415385,150,Style,Biratnagar,Adidas,Female,24.444444,30
4,5,Watch,Accessories,5500.000000,10.000000,4.500000,Out of Stock,TimeX,Kathmandu,Casio,Male,28.000000,80
5,6,Headphones,Electronics,4200.000000,9.333333,4.100000,75,AudioPro,Pokhara,JBL,Unisex,24.000000,65
6,7,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
7,8,Bag,Fashion,13883.333333,12.000000,3.900000,45,CarryAll,Dharan,Wildcraft,Female,19.000000,18
8,9,Mouse,Electronics,1800.000000,5.000000,4.300000,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
9,9,Cup,Electronics,1800.000000,5.000000,4.300000,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
10,10,Keyboard,Electronics,2500.000000,5.000000,4.400000,35,TechHub,Kathmandu,Logitech,Unisex,21.000000,110
11,11,Bottle,Home,800.000000,0.000000,5.500000,100,HomeStore,Janakpur,Generic,Unisex,26.000000,12
12,12,Chair,Furniture,-2500.000000,10.000000,4.000000,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44
13,12,Chair,Furniture,-2500.000000,10.000000,4.000000,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44

In [34]:
bdd.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        14 non-null     int64
 1   product_name      14 non-null     str
 2   category          14 non-null     str
 3   price             14 non-null     float64
 4   discount_percent  14 non-null     float64
 5   rating            14 non-null     float64
 6   stock             12 non-null     str
 7   seller            14 non-null     str
 8   city              14 non-null     str
 9   brand             14 non-null     str
 10  gender_target     14 non-null     str
 11  age               14 non-null     float64
 12  reviews           14 non-null     int64
dtypes: float64(4), int64(2), str(7)
memory usage: 1.6 KB

In [37]:
# bdd.duplicated()   # detect complete duplication row
# bdd.duplicated().sum()  # detect number of complete duplication rows
bdd[bdd.duplicated()]   # show duplicated rows from data set

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
13,12,Chair,Furniture,-2500.0,10.0,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44

In [39]:
# bdd.duplicated("product_id")  # find out duplication
bdd[bdd.duplicated("product_id")]  # show duplicated rows from dataset

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
9,9,Cup,Electronics,1800.0,5.0,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
13,12,Chair,Furniture,-2500.0,10.0,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44

In [42]:
bdd.drop_duplicates(inplace = True)   # delete duplicated rows and update datasets
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
1,2,Phone,Electronics,13883.333333,15.000000,4.600000,40,GadgetNepal,Pokhara,Samsung,Unisex,30.000000,210
2,3,Shoes,Fashion,3500.000000,9.333333,4.200000,60,FashionHub,Itahari,Nike,Male,22.000000,55
3,4,T-Shirt,Fashion,1500.000000,20.000000,4.415385,150,Style,Biratnagar,Adidas,Female,24.444444,30
4,5,Watch,Accessories,5500.000000,10.000000,4.500000,Out of Stock,TimeX,Kathmandu,Casio,Male,28.000000,80
5,6,Headphones,Electronics,4200.000000,9.333333,4.100000,75,AudioPro,Pokhara,JBL,Unisex,24.000000,65
6,7,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
7,8,Bag,Fashion,13883.333333,12.000000,3.900000,45,CarryAll,Dharan,Wildcraft,Female,19.000000,18
8,9,Mouse,Electronics,1800.000000,5.000000,4.300000,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
9,9,Cup,Electronics,1800.000000,5.000000,4.300000,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
10,10,Keyboard,Electronics,2500.000000,5.000000,4.400000,35,TechHub,Kathmandu,Logitech,Unisex,21.000000,110
11,11,Bottle,Home,800.000000,0.000000,5.500000,100,HomeStore,Janakpur,Generic,Unisex,26.000000,12
12,12,Chair,Furniture,-2500.000000,10.000000,4.000000,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44

In [49]:
# partial duplication delete and update datasets

bdd.drop_duplicates(subset = "product_id", keep="first", inplace=True)   # delete duplicated row which is below
bdd
# bdd.drop_duplicates(subset = "product_id", keep="last", inplace=True)  # delete duplicated row which is above

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
1,2,Phone,Electronics,13883.333333,15.000000,4.600000,40,GadgetNepal,Pokhara,Samsung,Unisex,30.000000,210
2,3,Shoes,Fashion,3500.000000,9.333333,4.200000,60,FashionHub,Itahari,Nike,Male,22.000000,55
3,4,T-Shirt,Fashion,1500.000000,20.000000,4.415385,150,Style,Biratnagar,Adidas,Female,24.444444,30
4,5,Watch,Accessories,5500.000000,10.000000,4.500000,Out of Stock,TimeX,Kathmandu,Casio,Male,28.000000,80
5,6,Headphones,Electronics,4200.000000,9.333333,4.100000,75,AudioPro,Pokhara,JBL,Unisex,24.000000,65
6,7,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
7,8,Bag,Fashion,13883.333333,12.000000,3.900000,45,CarryAll,Dharan,Wildcraft,Female,19.000000,18
8,9,Mouse,Electronics,1800.000000,5.000000,4.300000,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
10,10,Keyboard,Electronics,2500.000000,5.000000,4.400000,35,TechHub,Kathmandu,Logitech,Unisex,21.000000,110
11,11,Bottle,Home,800.000000,0.000000,5.500000,100,HomeStore,Janakpur,Generic,Unisex,26.000000,12
12,12,Chair,Furniture,-2500.000000,10.000000,4.000000,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44

In [53]:
# find out negative value 
bdd[bdd["price"]<0]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
12,12,Chair,Furniture,-2500.0,10.0,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44

In [67]:
# find out rating more than 5
bdd[bdd["rating"]>5]

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
11,11,Bottle,Home,800.0,0.0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12

In [61]:
# using loc, detect condition and set to zero 

bdd.loc[bdd["price"]<0 , "price"]=0
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
1,2,Phone,Electronics,13883.333333,15.000000,4.600000,40,GadgetNepal,Pokhara,Samsung,Unisex,30.000000,210
2,3,Shoes,Fashion,3500.000000,9.333333,4.200000,60,FashionHub,Itahari,Nike,Male,22.000000,55
3,4,T-Shirt,Fashion,1500.000000,20.000000,4.415385,150,Style,Biratnagar,Adidas,Female,24.444444,30
4,5,Watch,Accessories,5500.000000,10.000000,4.500000,Out of Stock,TimeX,Kathmandu,Casio,Male,28.000000,80
5,6,Headphones,Electronics,4200.000000,9.333333,4.100000,75,AudioPro,Pokhara,JBL,Unisex,24.000000,65
6,7,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
7,8,Bag,Fashion,13883.333333,12.000000,3.900000,45,CarryAll,Dharan,Wildcraft,Female,19.000000,18
8,9,Mouse,Electronics,1800.000000,5.000000,4.300000,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
10,10,Keyboard,Electronics,2500.000000,5.000000,4.400000,35,TechHub,Kathmandu,Logitech,Unisex,21.000000,110
11,11,Bottle,Home,800.000000,0.000000,5.500000,100,HomeStore,Janakpur,Generic,Unisex,26.000000,12
12,12,Chair,Furniture,0.000000,10.000000,4.000000,-5,FurniCo,Lalitpur,IKEA,Unisex,24.444444,44

In [66]:
# to delete rows having negative value and update datsets

bdd = bdd[bdd["price"]>0]
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
1,2,Phone,Electronics,13883.333333,15.000000,4.600000,40,GadgetNepal,Pokhara,Samsung,Unisex,30.000000,210
2,3,Shoes,Fashion,3500.000000,9.333333,4.200000,60,FashionHub,Itahari,Nike,Male,22.000000,55
3,4,T-Shirt,Fashion,1500.000000,20.000000,4.415385,150,Style,Biratnagar,Adidas,Female,24.444444,30
4,5,Watch,Accessories,5500.000000,10.000000,4.500000,Out of Stock,TimeX,Kathmandu,Casio,Male,28.000000,80
5,6,Headphones,Electronics,4200.000000,9.333333,4.100000,75,AudioPro,Pokhara,JBL,Unisex,24.000000,65
6,7,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
7,8,Bag,Fashion,13883.333333,12.000000,3.900000,45,CarryAll,Dharan,Wildcraft,Female,19.000000,18
8,9,Mouse,Electronics,1800.000000,5.000000,4.300000,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
10,10,Keyboard,Electronics,2500.000000,5.000000,4.400000,35,TechHub,Kathmandu,Logitech,Unisex,21.000000,110
11,11,Bottle,Home,800.000000,0.000000,5.500000,100,HomeStore,Janakpur,Generic,Unisex,26.000000,12

In [77]:
bdd.loc[bdd["rating"]>5, "rating"]=5
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
1,2,Phone,Electronics,13883.333333,15.000000,4.600000,40,GadgetNepal,Pokhara,Samsung,Unisex,30.000000,210
2,3,Shoes,Fashion,3500.000000,9.333333,4.200000,60,FashionHub,Itahari,Nike,Male,22.000000,55
3,4,T-Shirt,Fashion,1500.000000,20.000000,4.415385,150,Style,Biratnagar,Adidas,Female,24.444444,30
4,5,Watch,Accessories,5500.000000,10.000000,4.500000,Out of Stock,TimeX,Kathmandu,Casio,Male,28.000000,80
5,6,Headphones,Electronics,4200.000000,9.333333,4.100000,75,AudioPro,Pokhara,JBL,Unisex,24.000000,65
6,7,Laptop,Electronics,75000.000000,10.000000,4.800000,25,TechHub,Kathmandu,Dell,Unisex,25.000000,120
7,8,Bag,Fashion,13883.333333,12.000000,3.900000,45,CarryAll,Dharan,Wildcraft,Female,19.000000,18
8,9,Mouse,Electronics,1800.000000,5.000000,4.300000,NaN,TechHub,Kathmandu,Logitech,Unisex,24.444444,90
10,10,Keyboard,Electronics,2500.000000,5.000000,4.400000,35,TechHub,Kathmandu,Logitech,Unisex,21.000000,110
11,5,Bottle,Home,800.000000,0.000000,5.000000,100,HomeStore,Janakpur,Generic,Unisex,26.000000,12

In [82]:
# bdd["city"].str.strip()  # both side ko whitespace remove
# bdd["city"].str.lstrip()  # right side ko whitespace remove
# bdd["city"].str.rstrip()   # left side ko whitespace remove

# bdd["city"].str.upper()   # upper case
# bdd["city"].str.lower()   # lower case
# bdd["city"].str.title()   # first character upper and other lower

0      KaThmandu
1        Pokhara
2        Itahari
3     Biratnagar
4      KATHMANDU
5        Pokhara
6      Kathmandu
7         Dharan
8      Kathmandu
9      Kathmandu
10     KAthmandu
11      Janakpur
12      Lalitpur
13      Lalitpur
Name: city, dtype: str

In [88]:
bdd["city"] = bdd["city"].str.strip()
bdd["city"] = bdd["city"].str.title()
bdd["city"]

0      Kathmandu
1        Pokhara
2        Itahari
3     Biratnagar
4      Kathmandu
5        Pokhara
6      Kathmandu
7         Dharan
8      Kathmandu
9      Kathmandu
10     Kathmandu
11      Janakpur
12      Lalitpur
13      Lalitpur
Name: city, dtype: str