In [1]:
import pandas as pd

In [3]:
bdd = pd.read_csv("../datasets/bad_daraz_dataset.csv")
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,KaThmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,KATHMANDU,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,KAthmandu,Logitech,Unisex,21,110
11,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
13,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [7]:
# grouping 
bdd.groupby("category")

In [18]:
# to have a look on output 

for category,data in bdd.groupby("category"):
    print(category)
    print("Rows", len(data))
    print(data)

Accessories
Rows 1
   product_id product_name     category price discount_percent  rating  \
4           5        Watch  Accessories  5500               10     4.5

          stock seller       city  brand gender_target age  reviews
4  Out of Stock  TimeX  KATHMANDU  Casio          Male  28       80
Electronics
Rows 7
    product_id product_name     category  price discount_percent  rating  \
0            1       Laptop  Electronics  75000               10     4.8
1            2        Phone  Electronics    NaN               15     4.6
5            6   Headphones  Electronics   4200              NaN     4.1
6            7       Laptop  Electronics  75000               10     4.8
8            9        Mouse  Electronics   1800                5     4.3
9            9          Cup  Electronics   1800                5     4.3
10          10     Keyboard  Electronics   2500                5     4.4

   stock       seller         city     brand gender_target   age  reviews
0     25      TechHub    KaThmandu      Dell        Unisex    25      120
1     40  GadgetNepal      Pokhara   Samsung        Unisex    30      210
5     75     AudioPro      Pokhara       JBL        Unisex   24        65
6     25      TechHub    Kathmandu      Dell        Unisex    25      120
8    NaN      TechHub    Kathmandu  Logitech        Unisex   NaN       90
9    NaN      TechHub    Kathmandu  Logitech        Unisex   NaN       90
10    35     TechHub    KAthmandu   Logitech        Unisex    21      110
Fashion
Rows 3
   product_id product_name category price discount_percent  rating stock  \
2           3        Shoes  Fashion  3500               5%     4.2    60
3           4      T-Shirt  Fashion  1500               20     NaN   150
7           8          Bag  Fashion   abc               12     3.9    45

       seller        city      brand gender_target     age  reviews
2  FashionHub     Itahari       Nike          Male      22       55
3       Style  Biratnagar     Adidas        Female  Female       30
7    CarryAll      Dharan  Wildcraft        Female      19       18
Furniture
Rows 2
    product_id product_name   category  price discount_percent  rating stock  \
12          12        Chair  Furniture  -2500               10     4.0    -5
13          12        Chair  Furniture  -2500               10     4.0    -5

     seller      city brand gender_target      age  reviews
12  FurniCo  Lalitpur  IKEA        Unisex  Unknown       44
13  FurniCo  Lalitpur  IKEA        Unisex  Unknown       44
Home
Rows 1
    product_id product_name category price discount_percent  rating stock  \
11          11       Bottle     Home   800                0     5.5   100

       seller      city    brand gender_target age  reviews
11  HomeStore  Janakpur  Generic        Unisex  26       12

In [24]:
# individual category
Electronics = bdd.groupby("category").get_group("Electronics")
Electronics

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,KaThmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
10,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,KAthmandu,Logitech,Unisex,21,110

In [23]:

Fashion = bdd.groupby("category").get_group("Fashion")
Fashion

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18

In [28]:
for city,data in bdd.groupby("city"):
    print(city)

 KAthmandu
Biratnagar
Dharan
Itahari
Janakpur
KATHMANDU
KaThmandu
Kathmandu
Lalitpur
Pokhara

In [33]:
kathmandu = bdd.groupby("city").get_group("Kathmandu")
kathmandu

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,9,Cup,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90

In [34]:
# count() (grouping and aggregation)
bdd.groupby("category")["product_name"].count()

category
Accessories    1
Electronics    7
Fashion        3
Furniture      2
Home           1
Name: product_name, dtype: int64

In [37]:
# max() (grouping and aggregation)
bdd.groupby("category")["price"].max()

category
Accessories     5500
Electronics     1800
Fashion         1500
Furniture      -2500
Home             800
Name: price, dtype: str

In [38]:
# min() (grouping and aggregation)
bdd.groupby("category")["price"].min()

category
Accessories     5500
Electronics     1800
Fashion         1500
Furniture      -2500
Home             800
Name: price, dtype: str

In [39]:
# max(),min() and count() (grouping and multiple aggregation)
bdd.groupby("category")["price"].agg(["max","min","count"])

               max    min  count
category
Accessories   5500   5500      1
Electronics  75000   1800      6
Fashion        abc   1500      3
Furniture    -2500  -2500      2
Home           800    800      1

In [43]:
# grouping plus muptiple aggregation
# bdd.groupby("category")["rating"].min()
bdd.groupby("category").agg({
    "price" : "min",
    "rating" : "max",
    "reviews" : "sum"
})

             price  rating  reviews
category
Accessories   5500     4.5       80
Electronics   1800     4.8      805
Fashion       1500     4.2      103
Furniture    -2500     4.0       88
Home           800     5.5       12