In [1]:
import pandas as pd

In [3]:
lms = pd.read_csv("datasets/LMS_Dirty_Dataset.csv")
lms

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [8]:
# first 10 records
lms.head(10)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
5,6,Anisha,Data Science,Dharan,18,Male,2026-04-30,7000,10,Paid,57.0,70,70,4,Samriddha,9838336446,user5@gmail.com,Completed
6,7,Suman,MERN Stack,Dharan,33,Female,2026-05-03,5000,0,Paid,52.0,38,39,4,Ishan,9806614065,user6@gmail.com,Completed
7,8,Sita,MERN Stack,Pokhara,28,Female,2026-06-23,5000,20,Pending,71.0,38,98,5,Samriddha,9879884445,user7@gmail.com,Completed
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,-5000,10,Pending,70.0,88,98,4,Ishan,9869507556,user8@gmail.com,Completed
9,10,Sita,Flutter,Dharan,25,Female,2026-01-15,5000,20,Pending,53.0,88,47,3,Manish,9896293519,user9@gmail.com,Completed

In [9]:
# last 10 records
lms.tail(10)

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
340,341,Hari,Digital Marketing,Biratnagar,31,Female,2026-06-10,5000,20,Pending,96.0,38,71,5,Ishan,9831430348,user340@gmail.com,Ongoing
341,342,Gita,Flutter,Biratnagar,32,Female,2026-04-16,5000,10,Paid,54.0,33,61,5,Ishan,9865928299,user341@gmail.com,Ongoing
342,343,Aarav,UI/UX,Itahari,18,Male,2026-03-01,7000,10,Paid,45.0,85,46,5,Manish,9832055006,user342@gmail.com,Completed
343,344,Gita,Python with AI/ML,Kathmandu,33,Male,2026-05-07,5000,20,Paid,67.0,57,30,4,Samriddha,9828498406,user343@gmail.com,Ongoing
344,345,Gita,Digital Marketing,Pokhara,29,Male,2026-05-18,10000,10,Paid,71.0,45,89,4,Manish,9847970014,user344@gmail.com,Completed
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [11]:
# dataset shape
lms.shape

(350, 18)

In [18]:
# Columns Name 
lms.columns

Index(['student_id', 'student_name', 'course', 'city', 'age', 'gender',
       'enrollment_date', 'course_fee', 'discount', 'payment_status',
       'attendance_percent', 'assignment_score', 'final_score', 'rating',
       'mentor', 'phone', 'email', 'completion_status'],
      dtype='str')

In [19]:
# datasets info summary
lms.info()

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          350 non-null    int64
 1   student_name        350 non-null    str
 2   course              350 non-null    str
 3   city                350 non-null    str
 4   age                 350 non-null    int64
 5   gender              350 non-null    str
 6   enrollment_date     350 non-null    str
 7   course_fee          350 non-null    int64
 8   discount            350 non-null    int64
 9   payment_status      350 non-null    str
 10  attendance_percent  349 non-null    float64
 11  assignment_score    350 non-null    int64
 12  final_score         350 non-null    int64
 13  rating              350 non-null    int64
 14  mentor              350 non-null    str
 15  phone               350 non-null    str
 16  email               350 non-null    str
 17  completion_status   350 non-null    str
dtypes: float64(1), int64(7), str(10)
memory usage: 49.3 KB

In [20]:
# summary statistic of numeric columns\
lms.describe()

,student_id,age,course_fee,discount,attendance_percent,assignment_score,final_score,rating
count,350.000000,350.000000,350.000000,350.000000,349.000000,350.000000,350.000000,350.000000
mean,175.500000,26.174286,10085.711429,9.600000,70.154728,67.011429,65.011429,3.960000
std,101.180532,5.485686,53109.214627,7.929489,16.697929,20.686773,20.556718,0.817852
min,1.000000,17.000000,-5000.000000,0.000000,40.000000,-5.000000,30.000000,3.000000
25%,88.250000,21.000000,5000.000000,0.000000,58.000000,51.000000,47.000000,3.000000
50%,175.500000,27.000000,7000.000000,10.000000,70.000000,69.000000,65.000000,4.000000
75%,262.750000,31.000000,10000.000000,20.000000,83.000000,85.750000,82.000000,5.000000
max,350.000000,35.000000,999999.000000,20.000000,100.000000,100.000000,100.000000,5.000000

In [26]:
# identify duplicated records
lms.duplicated()
lms.duplicated().sum()

np.int64(0)

In [30]:
# detect missing values
lms.isnull().sum()

student_id            0
student_name          0
course                0
city                  0
age                   0
gender                0
enrollment_date       0
course_fee            0
discount              0
payment_status        0
attendance_percent    1
assignment_score      0
final_score           0
rating                0
mentor                0
phone                 0
email                 0
completion_status     0
dtype: int64

In [36]:
# found of in which row the null value is in 
lms[lms["attendance_percent"].isnull()]

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
28,29,Gita,MERN Stack,Biratnagar,29,Male,2026-03-13,7000,10,Pending,NaN,98,80,5,Samriddha,9822305489,user28@gmail.com,Ongoing

In [39]:
# handle missing value with median 
lms["attendance_percent"] = lms["attendance_percent"].fillna(lms["attendance_percent"].median())

In [44]:
# detect incorrect datatype
lms.dtypes

student_id              int64
student_name              str
course                    str
city                      str
age                     int64
gender                    str
enrollment_date           str
course_fee              int64
discount                int64
payment_status            str
attendance_percent    float64
assignment_score        int64
final_score             int64
rating                  int64
mentor                    str
phone                     str
email                     str
completion_status         str
dtype: object

In [46]:
# convert "enrollment_date" to date and time format
lms["enrollment_date"] = pd.to_datetime(lms["enrollment_date"])

In [50]:
lms

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,MERN Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,user0@gmail.com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,user1@gmail.com,Completed
2,3,Gita,MERN Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,user2@gmail.com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,user3@gmail.com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,user4@gmail.com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,UI/UX,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,user345@gmail.com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,user346@gmail.com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,user347@gmail.com,Completed
348,349,Anisha,UI/UX,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,user348@gmail.com,Completed
349,350,Hari,Python with AI/ML,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,user349@gmail.com,Ongoing

In [57]:
# filter columns with string datatype only
string_columns = lms.select_dtypes(include= ['object', 'string']).columns
string_columns

Index(['student_name', 'course', 'city', 'gender', 'payment_status', 'mentor',
       'phone', 'email', 'completion_status'],
      dtype='str')

In [59]:
# standarize string values
for column in string_columns:
    lms[column] = lms[column].str.strip().str.title()

lms

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
0,1,Gita,Mern Stack,Kathmandu,17,Female,2026-02-24,10000,10,Pending,73.0,46,98,5,Samriddha,9839323411,User0@Gmail.Com,Ongoing
1,2,Nabin,Data Science,Itahari,29,Female,2026-06-29,10000,20,Pending,68.0,31,63,3,Manish,9874340113,User1@Gmail.Com,Completed
2,3,Gita,Mern Stack,Dharan,20,Female,2026-02-20,5000,20,Paid,71.0,31,99,5,Samriddha,9874168652,User2@Gmail.Com,Completed
3,4,Gita,Digital Marketing,Itahari,20,Female,2026-05-23,7000,0,Pending,88.0,43,38,5,Manish,9864252889,User3@Gmail.Com,Ongoing
4,5,Gita,Data Science,Itahari,19,Male,2026-05-28,5000,0,Pending,100.0,89,98,5,Ishan,9864166467,User4@Gmail.Com,Ongoing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,346,Hari,Ui/Ux,Dharan,21,Female,2026-06-17,10000,20,Paid,98.0,87,56,5,Samriddha,9873827203,User345@Gmail.Com,Ongoing
346,347,Anisha,Digital Marketing,Biratnagar,31,Female,2026-03-21,5000,10,Paid,45.0,51,44,3,Samriddha,9864328504,User346@Gmail.Com,Ongoing
347,348,Sita,Flutter,Biratnagar,19,Male,2026-02-05,5000,20,Paid,80.0,89,39,5,Samriddha,9821459197,User347@Gmail.Com,Completed
348,349,Anisha,Ui/Ux,Itahari,27,Male,2026-05-05,5000,10,Paid,63.0,58,52,5,Ishan,9862269669,User348@Gmail.Com,Completed
349,350,Hari,Python With Ai/Ml,Dharan,19,Female,2026-04-04,5000,20,Pending,84.0,57,62,3,Manish,9803556080,User349@Gmail.Com,Ongoing

In [65]:
# detect neagtive value from all numeric columns
numeric_column = ['student_id','age','course_fee','discount','assignment_score','final_score','rating','attendance_percent']

for column in numeric_column:
    print(f"{column} : {(lms[column] < 0).sum()} negative value")

student_id : 0 negative value
age : 0 negative value
course_fee : 1 negative value
discount : 0 negative value
assignment_score : 1 negative value
final_score : 0 negative value
rating : 0 negative value
attendance_percent : 0 negative value

In [68]:
# detect negative value from specific column
lms[lms["course_fee"] <0 ]

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status
8,9,Gita,Flutter,Biratnagar,31,Male,2026-05-06,-5000,10,Pending,70.0,88,98,4,Ishan,9869507556,User8@Gmail.Com,Completed

In [76]:
# replace value 
lms.loc[lms["course_fee"]<0,"course_fee"] = 500

In [77]:
# detect negative value from specific column
lms[lms["assignment_score"] <0 ]

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status,assignmant_score
38,39,Anisha,Data Science,Itahari,20,Female,2026-01-14,10000,10,Pending,70.0,-5,55,3,Manish,9856058698,User38@Gmail.Com,Ongoing,5.0

In [97]:
# replace value 
lms.loc[lms["assignment_score"] <0, "assignment_score"]= 5

In [116]:
# outliers by IQR

Q1 = lms["course_fee"].quantile(0.25)
Q1

np.float64(5000.0)

In [117]:
Q3 = lms["course_fee"].quantile(0.75)
Q3

np.float64(10000.0)

In [118]:
IQR = Q3-Q1
IQR

np.float64(5000.0)

In [119]:
lower_bound = Q1-1.5*IQR
lower_bound

np.float64(-2500.0)

In [120]:
uppeer_bound = Q3+1.5*IQR
upper_bound

np.float64(17500.0)

In [121]:
outlier = lms[(lms["course_fee"] < lower_bound)|(lms["course_fee"] > upper_bound)]
outlier

,student_id,student_name,course,city,age,gender,enrollment_date,course_fee,discount,payment_status,attendance_percent,assignment_score,final_score,rating,mentor,phone,email,completion_status,assignmant_score
18,19,Sita,Flutter,Kathmandu,24,Male,2026-05-09,999999,10,Pending,41.0,75,51,4,Ishan,9803681891,User18@Gmail.Com,Ongoing,NaN